# Generated by Django 4.2.8 on 2023-12-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_school_person_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='98682', max_length=15),
            preserve_default=False,
        ),
    ]
