# Generated by Django 4.2.8 on 2023-12-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
