# Generated by Django 4.2.8 on 2023-12-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_school_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='person_photos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='dashboard.school'),
        ),
    ]
