# Generated by Django 4.2.8 on 2023-12-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_person_photo_alter_person_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='person_photos/avatar.png', upload_to='person_photos'),
        ),
    ]
